# Generated by Django 2.1.5 on 2019-02-13 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tableorder',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
    ]
