# Generated by Django 2.1.5 on 2019-01-28 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20190127_1916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='table',
        ),
        migrations.AlterField(
            model_name='table',
            name='max_customers',
            field=models.IntegerField(default=0),
        ),
    ]
